### PR TITLE
JBMAR-189: Prevent race condition in SerializableClassRegistry.lookup

### PR DESCRIPTION
**Pull request by ossnms**
UnlockedHashMap.doPut has a race condition related with the resizing of its internal table structure, because it has a flawed lock-free implementation. Replaced UnlockedHashMap with ConcurrentHashMap and adjusted SerializableClassRegistry.lookup to handle null classloader references (which are not supported by ConcurrentHashMap as keys).

### CODE REVIEW

**Comment by ossnms** [comment]
Fixed rebase.

**Comment by jglick** [comment]
@dmlloyd this is an important fix; is a `1.4.12.Final` forthcoming?

**Comment by jglick** [comment]
Hmm, 1c12cf1eb48d7b0f2459ca87f3a8a1d716dafb37 claims to have prepared it, yet [Central does not have it](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.jboss.marshalling%22%20AND%20a%3A%22jboss-marshalling-river%22)…and #37 has also been ignored for years. Sounds like I need to make my own private release.

**Comment by dmlloyd** [comment]
Looks like the artifact repository never got deployed.  I'll add it to the list for the next batch.

**Pull request merged**
