### PR TITLE
[JBMAR-234] Postponing sun.misc.Unsafe class initialization after doPrivileged() method call

### PR DESCRIPTION
**Pull request by ropalka**
https://issues.redhat.com/browse/JBMAR-234

### CODE REVIEW

**Comment by dmlloyd** [comment]
I don't like adding in the indirection on the hot path.  Couldn't the problem be fixed by forcing the class(es) to be initialized earlier (i.e. during app server startup)?

**Comment by dmlloyd** [comment]
Or by adding a privileged block at Protocol.java:200 perhaps?  I don't have the code up but it seems that there is a point where JBMAR has control at this line (based on the stack trace).

**Comment by ropalka** [comment]
> I don't like adding in the indirection on the hot path. Couldn't the problem be fixed by forcing the class(es) to be initialized earlier (i.e. during app server startup)?

That sounds hacky. I wouldn't go that way.

**Comment by ropalka** [comment]
> Or by adding a privileged block at Protocol.java:200 perhaps? I don't have the code up but it seems that there is a point where JBMAR has control at this line (based on the stack trace).

You meant Protocol.java:220 obviously. There is doPrivileged block already there. @darranl suspects the issue is org.jboss.marshalling.river.Protocol itself containing a reference to sun.misc.Unsafe and at the time the class is being loaded the callers ProtectionDomain is still on the stack - see our discussion @dmlloyd on ZULIP in stream #wildlfy-elytron #WFLY-14077

**Comment by ropalka** [comment]
PR force updated. Initialization happens only once - first time the Unsafe wrapper interface is loaded.
Unfortunately wrapper over sun.misc.Unsafe is still there.

**Comment by ropalka** [comment]
The problem was fixed inside JDK 11.0.10 and so this workaround is not needed anymore. I am closing this PR @dmlloyd .

**Pull request closed without merging**
