### PR TITLE
JBMAR-193 Filter Incoming Marshalling Data

### PR DESCRIPTION
**Pull request by kurobako**
https://issues.jboss.org/browse/JBMAR-193

### CODE REVIEW

**Comment by kurobako** [comment]
WIP

**Comment by kurobako** [comment]
@dmlloyd could you please give some feedback on this?

**Comment by dmlloyd** [comment]
Sure, sorry I missed the initial notification.

In the JDK, the ObjectInputFilter.FilterInfo structure (Java 9 and later) contains additional fields beyond the current class including:

* `arrayLength()` - the number of array elements in the current object
* `depth()` - the current depth
* `references()` - the number of object references
* `streamBytes()` - the number of stream bytes consumed

The whole object structure is assembled and passed to the filter which makes a decision on all at once.  In contrast, the proposed filter interface must evaluate each criterion independently and without context.  Is the array too big?  What if it depends on the array type?  I think that to get feature parity with the JDK, we should be replicating its interface (with our interface extend the JDK one on Java 9+, ultimately migrating to `ObjectInputFilter` and `FilterInfo` once our minimum requirement moves beyond Java 8).  This will also allow us to use the globally installed object filter on Java 9+ by way of a trivial wrapper utility.  We'd want to verify (on both Java 8 through custom code and Java 9+ through the global serialization config) that the `jdk.serialFilter` property is correctly being applied.

Ideally the filter mechanism would allow for filtering by class name before the class is loaded, but the JDK does not support this, so I suppose we need not support this either.

**Comment by kurobako** [comment]
@dmlloyd I updated this PR, could you please take another look?
I thought it might be good style to have code parsing the jdk.serialFilter property and creating InputFilter instance in wildfly rather than built-in into marshalling, what do you think?

**Pull request closed without merging**
