### PR TITLE
[JBMAR-227] Improve performance of river marshalling of objects

### PR DESCRIPTION
**Pull request by fl4via**
Jira: https://issues.jboss.org/browse/JBMAR-227

### CODE REVIEW

**Comment by dmlloyd** [comment]
Is there data to support the idea that breaking up doWriteObject improves performance?

**Comment by dmlloyd** [comment]
I ask because it's going to make ongoing maintenance/backporting more difficult.

**Comment by fl4via** [comment]
@dmlloyd yes, this commit alone was able to shave 13 ms from the average time of  stateful session bean call; and 7 ms form the average time of stateless session bean calls in our tests.
jboss-ejb-client uses a lot of object marshalling and this was causing a big impact in the performance for those calls

**Comment by dmlloyd** [comment]
Do you have any theory as to why that might be the case?

**Comment by fl4via** [comment]
@dmlloyd yes, this is the theory from @stuartwdouglas :
 "my changes dropped it from 8226 bytes to 1300 bytes but that is still too big to inline
maybe it was just too big for the JVM to optimise efficently and dropping it down just improved the compiled code
In case anyone is wondering you can see this info with '-XX:+PrintCompilation -XX:+UnlockDiagnosticVMOptions -XX:+PrintInlining' , and you can see which methods are being inlined. If you see 'hot method too big' in the output it means that you might be able to get a performance improvement by reducing the size of the method, generally by moving lesser used code paths into their own method"

**Comment by fl4via** [comment]
@dmlloyd another theory is that with the change in branching logic, branch miss-predictions have decreased, something that could be analysed by a tool such as https://github.com/AdoptOpenJDK/jitwatch . I haven't checked those things, though

**Comment by dmlloyd** [comment]
I doubt inlining is a factor because all of these methods are far outside of what that would improve (what is the point of breaking up a method hoping the pieces would be inlined again?).

Branch prediction is a good hypothesis IMO: `switch` statements do not apply profiling logic so branch prediction effectively doesn't work on them, and `switch` is the basis of the unmarshalling logic.  It might be interesting to try converting (at least partially) the `switch` to an `if` as an isolated change to see if that makes the same difference.

**Comment by fl4via** [comment]
@dmlloyd sure, I can give it a try. However, I'll be able to do it tomorrow after I have raised all jiras and PRs/commits for the whole optimization package we've been working on. I'll let you know as soon as I have results for that

**Comment by stuartwdouglas** [comment]
I think the main benefit is short circuiting the switch for the case when the id is -1. This is a really common case for the objects used in the EJB protocol.

**Comment by fl4via** [comment]
@dmlloyd I had to postpone this due to other urgent things on my list,but I hope I'll be able to take a look at this later today

**Comment by ropalka** [comment]
Any progress on switch -> if conversion @fl4via ? I was asked if we could release JBMAR at the end of this week and I see this PR is still pending. Just FYI @fl4via and @dmlloyd I created more generic AccessController.doPrivileged() PR to address all cases of doPrivileged() calls in whole jboss-marshalling project.

**Comment by fl4via** [comment]
@ropalka @dmlloyd 
Unfortunately the issue is the size of the method. I ran the following test:
1. remove the optimization commit 
2. remove the new methods from the PR, moving back the code to the main method, but keeping the rest of the PR as is (i.e., keeping the if statements as they are)
3. run with the PR as is

On a SLSB micro benchmark invocation with 200 calls, I got the following numbers
                          1                         2                          3
pool size 10     57ms                 57 ms                  50 ms
pool size 20     58ms                 57 ms                  47 ms
pool size 30     56ms                 57 ms                  45 ms

As you can see, we have an impact of more than 10% in performance improvement

**Comment by fl4via** [comment]
@ropalka @dmlloyd since we are needing a new marshalling release with this fix, I'll go ahead and merge it. We can continue the discussion when you guys are available again, it would be ideal to get to a conclusion of all this and then apply the same performance improvement to readObject as well. Thanks for your feedback on this PR, btw!

**Pull request merged**
